import { CertificateTemplate, CANVAS_WIDTH, CANVAS_HEIGHT } from './types'

const W = CANVAS_WIDTH
const H = CANVAS_HEIGHT
const CX = W / 2

export const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
  {
    id: 'classic-academic',
    name: 'Classic Academic',
    category: 'academic',
    preview: { bg: '#FFF8F0', accent: '#8B6914', textColor: '#2D2006', borderColor: '#C9A84C' },
    canvas: { width: W, height: H, backgroundColor: '#FFF8F0' },
    elements: [
      { type: 'rect', left: 24, top: 24, width: W - 48, height: H - 48, fill: 'transparent', stroke: '#C9A84C', strokeWidth: 3, rx: 0, ry: 0, selectable: false },
      { type: 'rect', left: 32, top: 32, width: W - 64, height: H - 64, fill: 'transparent', stroke: '#C9A84C', strokeWidth: 1, rx: 0, ry: 0, selectable: false },
      { type: 'text', left: CX, top: 80, text: 'CERTIFICATE', fontSize: 18, fontFamily: 'Cinzel', fontWeight: '600', fill: '#8B6914', textAlign: 'center', charSpacing: 800 },
      { type: 'text', left: CX, top: 130, text: 'OF ACHIEVEMENT', fontSize: 36, fontFamily: 'Playfair Display', fontWeight: '700', fill: '#2D2006', textAlign: 'center' },
      { type: 'line', left: CX - 140, top: 185, width: 280, height: 0, stroke: '#C9A84C', strokeWidth: 1, x1: 0, y1: 0, x2: 280, y2: 0 },
      { type: 'text', left: CX, top: 210, text: 'This certificate is proudly presented to', fontSize: 16, fontFamily: 'Lora', fill: '#5A4A2E', textAlign: 'center', fontStyle: 'italic' },
      { type: 'text', left: CX, top: 270, text: '{{name}}', fontSize: 48, fontFamily: 'Great Vibes', fill: '#2D2006', textAlign: 'center' },
      { type: 'line', left: CX - 180, top: 330, width: 360, height: 0, stroke: '#C9A84C', strokeWidth: 1, x1: 0, y1: 0, x2: 360, y2: 0 },
      { type: 'text', left: CX, top: 360, text: 'For outstanding performance and dedication in', fontSize: 15, fontFamily: 'Lora', fill: '#5A4A2E', textAlign: 'center' },
      { type: 'text', left: CX, top: 400, text: '{{course}}', fontSize: 28, fontFamily: 'Playfair Display', fontWeight: '600', fill: '#2D2006', textAlign: 'center' },
      { type: 'text', left: CX, top: 470, text: 'Awarded on this day, {{date}}', fontSize: 14, fontFamily: 'Lora', fill: '#5A4A2E', textAlign: 'center', fontStyle: 'italic' },
      { type: 'line', left: 160, top: 600, width: 200, height: 0, stroke: '#5A4A2E', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: 260, top: 610, text: 'Signature', fontSize: 12, fontFamily: 'Lora', fill: '#8B6914', textAlign: 'center' },
      { type: 'line', left: W - 360, top: 600, width: 200, height: 0, stroke: '#5A4A2E', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: W - 260, top: 610, text: 'Date', fontSize: 12, fontFamily: 'Lora', fill: '#8B6914', textAlign: 'center' },
    ],
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'completion',
    preview: { bg: '#FFFFFF', accent: '#0F172A', textColor: '#0F172A', borderColor: '#E2E8F0' },
    canvas: { width: W, height: H, backgroundColor: '#FFFFFF' },
    elements: [
      { type: 'rect', left: 0, top: 0, width: 8, height: H, fill: '#0F172A', selectable: false },
      { type: 'text', left: 60, top: 80, text: 'CERTIFICATE', fontSize: 14, fontFamily: 'Montserrat', fontWeight: '600', fill: '#94A3B8', textAlign: 'left', charSpacing: 600 },
      { type: 'text', left: 60, top: 115, text: 'of Completion', fontSize: 42, fontFamily: 'Montserrat', fontWeight: '700', fill: '#0F172A', textAlign: 'left' },
      { type: 'rect', left: 60, top: 175, width: 60, height: 4, fill: '#0F172A' },
      { type: 'text', left: 60, top: 210, text: 'This is to certify that', fontSize: 15, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'left' },
      { type: 'text', left: 60, top: 260, text: '{{name}}', fontSize: 44, fontFamily: 'Montserrat', fontWeight: '700', fill: '#0F172A', textAlign: 'left' },
      { type: 'text', left: 60, top: 330, text: 'has successfully completed the course', fontSize: 15, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'left' },
      { type: 'text', left: 60, top: 370, text: '{{course}}', fontSize: 26, fontFamily: 'Montserrat', fontWeight: '600', fill: '#0F172A', textAlign: 'left' },
      { type: 'text', left: 60, top: 430, text: '{{date}}', fontSize: 14, fontFamily: 'Open Sans', fill: '#94A3B8', textAlign: 'left' },
      { type: 'line', left: 60, top: 580, width: 180, height: 0, stroke: '#CBD5E1', strokeWidth: 1, x1: 0, y1: 0, x2: 180, y2: 0 },
      { type: 'text', left: 150, top: 590, text: 'Instructor', fontSize: 12, fontFamily: 'Open Sans', fill: '#94A3B8', textAlign: 'center' },
      { type: 'line', left: 340, top: 580, width: 180, height: 0, stroke: '#CBD5E1', strokeWidth: 1, x1: 0, y1: 0, x2: 180, y2: 0 },
      { type: 'text', left: 430, top: 590, text: 'Director', fontSize: 12, fontFamily: 'Open Sans', fill: '#94A3B8', textAlign: 'center' },
    ],
  },
  {
    id: 'bold-achievement',
    name: 'Bold Achievement',
    category: 'achievement',
    preview: { bg: '#1A1A2E', accent: '#E2B93B', textColor: '#FFFFFF' },
    canvas: { width: W, height: H, backgroundColor: '#1A1A2E' },
    elements: [
      { type: 'rect', left: 20, top: 20, width: W - 40, height: H - 40, fill: 'transparent', stroke: '#E2B93B', strokeWidth: 2 },
      { type: 'rect', left: 0, top: 0, width: W, height: 6, fill: '#E2B93B', selectable: false },
      { type: 'rect', left: 0, top: H - 6, width: W, height: 6, fill: '#E2B93B', selectable: false },
      { type: 'circle', left: CX, top: 90, radius: 40, fill: 'transparent', stroke: '#E2B93B', strokeWidth: 2 },
      { type: 'text', left: CX, top: 75, text: '★', fontSize: 40, fontFamily: 'serif', fill: '#E2B93B', textAlign: 'center' },
      { type: 'text', left: CX, top: 160, text: 'CERTIFICATE OF', fontSize: 14, fontFamily: 'Montserrat', fontWeight: '600', fill: '#E2B93B', textAlign: 'center', charSpacing: 600 },
      { type: 'text', left: CX, top: 200, text: 'ACHIEVEMENT', fontSize: 48, fontFamily: 'Cinzel', fontWeight: '700', fill: '#FFFFFF', textAlign: 'center' },
      { type: 'text', left: CX, top: 275, text: 'Awarded to', fontSize: 16, fontFamily: 'Open Sans', fill: '#A0A0B8', textAlign: 'center' },
      { type: 'text', left: CX, top: 320, text: '{{name}}', fontSize: 44, fontFamily: 'Great Vibes', fill: '#E2B93B', textAlign: 'center' },
      { type: 'line', left: CX - 150, top: 375, width: 300, height: 0, stroke: '#E2B93B', strokeWidth: 1, x1: 0, y1: 0, x2: 300, y2: 0 },
      { type: 'text', left: CX, top: 400, text: 'In recognition of exceptional achievement in', fontSize: 14, fontFamily: 'Open Sans', fill: '#A0A0B8', textAlign: 'center' },
      { type: 'text', left: CX, top: 440, text: '{{course}}', fontSize: 26, fontFamily: 'Montserrat', fontWeight: '600', fill: '#FFFFFF', textAlign: 'center' },
      { type: 'text', left: CX, top: 500, text: '{{date}}', fontSize: 13, fontFamily: 'Open Sans', fill: '#A0A0B8', textAlign: 'center' },
      { type: 'line', left: 160, top: 620, width: 200, height: 0, stroke: '#E2B93B', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: 260, top: 632, text: 'Authorized Signature', fontSize: 11, fontFamily: 'Open Sans', fill: '#A0A0B8', textAlign: 'center' },
      { type: 'line', left: W - 360, top: 620, width: 200, height: 0, stroke: '#E2B93B', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: W - 260, top: 632, text: 'Date Issued', fontSize: 11, fontFamily: 'Open Sans', fill: '#A0A0B8', textAlign: 'center' },
    ],
  },
  {
    id: 'professional-blue',
    name: 'Professional Blue',
    category: 'completion',
    preview: { bg: '#EEF2FF', accent: '#3B82F6', textColor: '#1E293B', borderColor: '#3B82F6' },
    canvas: { width: W, height: H, backgroundColor: '#EEF2FF' },
    elements: [
      { type: 'rect', left: 0, top: 0, width: W, height: 120, fill: '#1E3A5F' },
      { type: 'text', left: CX, top: 35, text: 'CERTIFICATE OF COMPLETION', fontSize: 28, fontFamily: 'Montserrat', fontWeight: '700', fill: '#FFFFFF', textAlign: 'center' },
      { type: 'text', left: CX, top: 78, text: 'Professional Development Program', fontSize: 14, fontFamily: 'Open Sans', fill: '#93C5FD', textAlign: 'center' },
      { type: 'rect', left: 0, top: 120, width: W, height: 4, fill: '#3B82F6', selectable: false },
      { type: 'text', left: CX, top: 170, text: 'This certifies that', fontSize: 16, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'center' },
      { type: 'text', left: CX, top: 220, text: '{{name}}', fontSize: 46, fontFamily: 'Playfair Display', fontWeight: '700', fill: '#1E293B', textAlign: 'center' },
      { type: 'line', left: CX - 160, top: 280, width: 320, height: 0, stroke: '#3B82F6', strokeWidth: 2, x1: 0, y1: 0, x2: 320, y2: 0 },
      { type: 'text', left: CX, top: 305, text: 'has successfully completed all requirements for', fontSize: 15, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'center' },
      { type: 'text', left: CX, top: 350, text: '{{course}}', fontSize: 28, fontFamily: 'Montserrat', fontWeight: '600', fill: '#1E3A5F', textAlign: 'center' },
      { type: 'text', left: CX, top: 420, text: '{{date}}', fontSize: 14, fontFamily: 'Open Sans', fill: '#94A3B8', textAlign: 'center' },
      { type: 'rect', left: 0, top: H - 60, width: W, height: 60, fill: '#1E3A5F', selectable: false },
      { type: 'line', left: 120, top: 570, width: 200, height: 0, stroke: '#94A3B8', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: 220, top: 580, text: 'Program Director', fontSize: 11, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'center' },
      { type: 'line', left: W - 320, top: 570, width: 200, height: 0, stroke: '#94A3B8', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: W - 220, top: 580, text: 'Organization', fontSize: 11, fontFamily: 'Open Sans', fill: '#64748B', textAlign: 'center' },
    ],
  },
  {
    id: 'elegant-appreciation',
    name: 'Elegant Appreciation',
    category: 'appreciation',
    preview: { bg: '#FAF5FF', accent: '#7C3AED', textColor: '#1E1B4B', borderColor: '#A78BFA' },
    canvas: { width: W, height: H, backgroundColor: '#FAF5FF' },
    elements: [
      { type: 'rect', left: 30, top: 30, width: W - 60, height: H - 60, fill: 'transparent', stroke: '#A78BFA', strokeWidth: 1.5, rx: 12, ry: 12 },
      { type: 'text', left: CX, top: 80, text: '❦', fontSize: 36, fontFamily: 'serif', fill: '#A78BFA', textAlign: 'center' },
      { type: 'text', left: CX, top: 130, text: 'Certificate of Appreciation', fontSize: 38, fontFamily: 'Playfair Display', fontWeight: '700', fill: '#1E1B4B', textAlign: 'center' },
      { type: 'line', left: CX - 100, top: 185, width: 200, height: 0, stroke: '#A78BFA', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: CX, top: 215, text: 'This certificate is presented with gratitude to', fontSize: 15, fontFamily: 'Cormorant Garamond', fill: '#6B7280', textAlign: 'center', fontStyle: 'italic' },
      { type: 'text', left: CX, top: 270, text: '{{name}}', fontSize: 46, fontFamily: 'Great Vibes', fill: '#7C3AED', textAlign: 'center' },
      { type: 'text', left: CX, top: 350, text: 'For their outstanding contribution and dedication to', fontSize: 15, fontFamily: 'Cormorant Garamond', fill: '#6B7280', textAlign: 'center' },
      { type: 'text', left: CX, top: 390, text: '{{course}}', fontSize: 26, fontFamily: 'Playfair Display', fontWeight: '600', fill: '#1E1B4B', textAlign: 'center' },
      { type: 'text', left: CX, top: 450, text: 'Your efforts have made a meaningful difference.', fontSize: 14, fontFamily: 'Cormorant Garamond', fill: '#6B7280', textAlign: 'center', fontStyle: 'italic' },
      { type: 'text', left: CX, top: 500, text: '{{date}}', fontSize: 13, fontFamily: 'Open Sans', fill: '#A78BFA', textAlign: 'center' },
      { type: 'line', left: 160, top: 600, width: 200, height: 0, stroke: '#A78BFA', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: 260, top: 612, text: 'Presented by', fontSize: 11, fontFamily: 'Open Sans', fill: '#A78BFA', textAlign: 'center' },
      { type: 'line', left: W - 360, top: 600, width: 200, height: 0, stroke: '#A78BFA', strokeWidth: 1, x1: 0, y1: 0, x2: 200, y2: 0 },
      { type: 'text', left: W - 260, top: 612, text: 'Date', fontSize: 11, fontFamily: 'Open Sans', fill: '#A78BFA', textAlign: 'center' },
    ],
  },
  {
    id: 'vibrant-creative',
    name: 'Vibrant Creative',
    category: 'achievement',
    preview: { bg: '#FFF7ED', accent: '#EA580C', textColor: '#1C1917', borderColor: '#FB923C' },
    canvas: { width: W, height: H, backgroundColor: '#FFFBF5' },
    elements: [
      { type: 'rect', left: 0, top: 0, width: 40, height: H, fill: '#EA580C', selectable: false },
      { type: 'rect', left: 40, top: 0, width: 8, height: H, fill: '#FED7AA', selectable: false },
      { type: 'circle', left: W - 100, top: 100, radius: 60, fill: '#FED7AA', opacity: 0.5 },
      { type: 'circle', left: W - 60, top: 180, radius: 30, fill: '#FDBA74', opacity: 0.4 },
      { type: 'text', left: 100, top: 80, text: 'CERTIFICATE', fontSize: 14, fontFamily: 'Montserrat', fontWeight: '700', fill: '#EA580C', textAlign: 'left', charSpacing: 500 },
      { type: 'text', left: 100, top: 115, text: 'of Achievement', fontSize: 44, fontFamily: 'Poppins', fontWeight: '700', fill: '#1C1917', textAlign: 'left' },
      { type: 'rect', left: 100, top: 180, width: 80, height: 5, fill: '#EA580C', rx: 3, ry: 3 },
      { type: 'text', left: 100, top: 220, text: 'Proudly awarded to', fontSize: 15, fontFamily: 'Open Sans', fill: '#78716C', textAlign: 'left' },
      { type: 'text', left: 100, top: 270, text: '{{name}}', fontSize: 42, fontFamily: 'Poppins', fontWeight: '700', fill: '#EA580C', textAlign: 'left' },
      { type: 'text', left: 100, top: 340, text: 'For successfully completing', fontSize: 15, fontFamily: 'Open Sans', fill: '#78716C', textAlign: 'left' },
      { type: 'text', left: 100, top: 375, text: '{{course}}', fontSize: 26, fontFamily: 'Poppins', fontWeight: '600', fill: '#1C1917', textAlign: 'left' },
      { type: 'text', left: 100, top: 440, text: '{{date}}', fontSize: 14, fontFamily: 'Open Sans', fill: '#A8A29E', textAlign: 'left' },
      { type: 'line', left: 100, top: 580, width: 180, height: 0, stroke: '#D6D3D1', strokeWidth: 1, x1: 0, y1: 0, x2: 180, y2: 0 },
      { type: 'text', left: 190, top: 590, text: 'Signature', fontSize: 11, fontFamily: 'Open Sans', fill: '#A8A29E', textAlign: 'center' },
      { type: 'line', left: 380, top: 580, width: 180, height: 0, stroke: '#D6D3D1', strokeWidth: 1, x1: 0, y1: 0, x2: 180, y2: 0 },
      { type: 'text', left: 470, top: 590, text: 'Director', fontSize: 11, fontFamily: 'Open Sans', fill: '#A8A29E', textAlign: 'center' },
    ],
  },
]
